# Generated by Django 3.1.1 on 2021-02-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack', models.TextField(max_length=100, null=True, verbose_name='Pack')),
                ('image', models.CharField(max_length=500, null=True, verbose_name='Image')),
            ],
            options={
                'db_table': 'pack',
            },
        ),
    ]
