# Generated by Django 3.1.1 on 2021-02-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardpack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='name',
            field=models.TextField(max_length=100, null=True, verbose_name='Pack'),
        ),
    ]
