# Generated by Django 3.1.1 on 2021-02-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardpack', '0002_pack_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='description',
            field=models.TextField(max_length=500, null=True, verbose_name='Pack'),
        ),
    ]
