# Generated by Django 3.1.1 on 2021-02-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardpack', '0003_pack_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='link',
            field=models.CharField(max_length=100, null=True, verbose_name='Image'),
        ),
    ]
