# Generated by Django 3.1.1 on 2021-02-12 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardpack', '0005_auto_20210213_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='link',
        ),
    ]
