# Generated by Django 3.1.1 on 2021-02-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardpack', '0006_remove_pack_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Pack'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='name',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Pack'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='pack',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Pack'),
        ),
    ]
