# Generated by Django 3.1.1 on 2021-02-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardpack', '0007_auto_20210213_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='q1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Question1'),
        ),
        migrations.AddField(
            model_name='pack',
            name='q2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Question2'),
        ),
        migrations.AddField(
            model_name='pack',
            name='q3',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Question3'),
        ),
    ]
