# Generated by Django 3.1.1 on 2021-02-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, null=True, verbose_name='Version')),
                ('title', models.CharField(max_length=400, null=True, verbose_name='Title')),
                ('date', models.CharField(max_length=300, null=True, verbose_name='Date')),
                ('desc', models.CharField(max_length=500, null=True, verbose_name='Description')),
            ],
            options={
                'db_table': 'ChangeLog',
            },
        ),
    ]
