# Generated by Django 3.1.1 on 2021-02-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changelog',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='changelog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
