# Generated by Django 3.1.1 on 2021-02-05 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigDeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(null=True, verbose_name='Index')),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Level')),
                ('question', models.TextField(max_length=400, null=True, verbose_name='Question')),
                ('image', models.CharField(max_length=100, null=True, verbose_name='Image')),
            ],
            options={
                'db_table': 'DigDeeper',
            },
        ),
        migrations.CreateModel(
            name='IceBreak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(null=True, verbose_name='Index')),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Level')),
                ('question', models.TextField(max_length=400, null=True, verbose_name='Question')),
                ('image', models.CharField(max_length=100, null=True, verbose_name='Image')),
            ],
            options={
                'db_table': 'IceBreak',
            },
        ),
    ]
