# Generated by Django 3.1.1 on 2021-02-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_perspective'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigDeeper1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(null=True, verbose_name='Index')),
                ('question', models.TextField(max_length=400, null=True, verbose_name='Question')),
                ('image', models.CharField(max_length=100, null=True, verbose_name='Image')),
            ],
            options={
                'db_table': 'DigDeeper1',
            },
        ),
        migrations.CreateModel(
            name='DigDeeper2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(null=True, verbose_name='Index')),
                ('question', models.TextField(max_length=400, null=True, verbose_name='Question')),
                ('image', models.CharField(max_length=100, null=True, verbose_name='Image')),
            ],
            options={
                'db_table': 'DigDeeper2',
            },
        ),
        migrations.CreateModel(
            name='DigDeeper3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(null=True, verbose_name='Index')),
                ('question', models.TextField(max_length=400, null=True, verbose_name='Question')),
                ('image', models.CharField(max_length=100, null=True, verbose_name='Image')),
            ],
            options={
                'db_table': 'DigDeeper3',
            },
        ),
        migrations.DeleteModel(
            name='DigDeeper',
        ),
        migrations.RemoveField(
            model_name='icebreak',
            name='level',
        ),
        migrations.RemoveField(
            model_name='perspective',
            name='level',
        ),
    ]
