# Generated by Django 3.1.1 on 2021-02-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0007_mixnmatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digdeeper1',
            name='image',
            field=models.CharField(max_length=500, null=True, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='digdeeper2',
            name='image',
            field=models.CharField(max_length=500, null=True, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='digdeeper3',
            name='image',
            field=models.CharField(max_length=500, null=True, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='icebreak',
            name='image',
            field=models.CharField(max_length=500, null=True, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='lovebirds',
            name='image',
            field=models.CharField(max_length=500, null=True, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='mixnmatch',
            name='image',
            field=models.CharField(max_length=500, null=True, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='perspective',
            name='image',
            field=models.CharField(max_length=500, null=True, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='stranger',
            name='image',
            field=models.CharField(max_length=500, null=True, verbose_name='Image'),
        ),
    ]
