# Generated by Django 3.1.1 on 2021-02-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0008_auto_20210211_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionID', models.TextField(max_length=500, null=True, verbose_name='id')),
                ('pack', models.TextField(max_length=500, null=True, verbose_name='Pack')),
                ('report', models.TextField(max_length=300, null=True, verbose_name='Pack')),
                ('desc', models.TextField(max_length=900, null=True, verbose_name='Pack')),
            ],
            options={
                'db_table': 'Report',
            },
        ),
    ]
