# Generated by Django 3.1.1 on 2021-02-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0009_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='question',
            field=models.TextField(max_length=500, null=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='report',
            name='desc',
            field=models.TextField(max_length=900, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report',
            field=models.TextField(max_length=300, null=True, verbose_name='Issue'),
        ),
    ]
