# Generated by Django 3.1.1 on 2021-02-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0010_auto_20210213_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='question',
            field=models.TextField(max_length=500, null=True, verbose_name='Question'),
        ),
    ]
