# Generated by Django 3.1.1 on 2021-02-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0011_auto_20210213_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameplayRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(blank=True, max_length=100, null=True, verbose_name='Player')),
                ('pack', models.CharField(blank=True, max_length=200, null=True, verbose_name='Pack')),
                ('numOfCards', models.IntegerField(blank=True, null=True, verbose_name='Number of Cards')),
            ],
            options={
                'db_table': 'GameplayRecord',
            },
        ),
    ]
