# Generated by Django 3.1.1 on 2021-02-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0012_gameplayrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayrecord',
            name='numOfCards',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Number of Cards'),
        ),
    ]
