# Generated by Django 3.1.1 on 2021-02-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0013_auto_20210221_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayrecord',
            name='numOfCards',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Cards'),
        ),
    ]
