# Generated by Django 3.1.1 on 2021-02-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0014_auto_20210221_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayrecord',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameplayrecord',
            name='numOfCards',
            field=models.IntegerField(null=True, verbose_name='Number of Cards'),
        ),
    ]
