# Generated by Django 3.1.1 on 2021-02-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0015_auto_20210221_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayrecord',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='gameplayrecord',
            name='numOfCards',
            field=models.CharField(max_length=100, null=True, verbose_name='Number of Cards'),
        ),
    ]
